def swapFileData():
    file1 = input("Enter file path for file 1: ")
    file2 = input("Enter file path for file 2: ")
    file1Data_r = open(file1,'r')
    file2Data_r = open(file2,'r')
    data_a = file1Data_r.read()
    data_b = file2Data_r.read()
    file1Data_w = open(file1,'w')
    file2Data_w = open(file2,'w')
    file1Data_w.write(data_b) 
    file2Data_w.write(data_a)
    file1Data_r.close()
    file2Data_r.close()
    file2Data_w.close()
    file2Data_w.close()
swapFileData() 